package org.phoenixframework.core.executor;

import java.util.Collection;

/**
 * The <code>QueryExecutor</code> represents the basic mechanism for executing queries into database.
 *
 * @author Oleg Marchenko
 * @see org.phoenixframework.core.executor.CachedResultSet
 */

public interface QueryExecutor {

    /**
     * Executes the SQL query and returns the <code>CachedResultSet</code> object generated by the query.
     *
     * @param query SQL query to execute
     * @param params query parameters
     * @return a <code>CachedResultSet</code> object that contains the data produced by the
     *         query; never <code>null</code>
     */
    CachedResultSet executeQuery(String query, Object... params);

    /**
     * Executes the SQL query and returns the <code>CachedResultSet</code> object generated by the query.
     *
     * @param query SQL query to execute
     * @param params collection of query parameters
     * @return a <code>CachedResultSet</code> object that contains the data produced by the
     *         query; never <code>null</code>
     */
    CachedResultSet executeQuery(String query, Collection<Object> params);

    /**
     * Executes the SQL query, which must be an SQL Data Manipulation Language (DML) statement,
     * such as <code>INSERT</code>, <code>UPDATE</code> or <code>DELETE</code>;
     * or an SQL statement that returns nothing, such as a DDL statement.
     *
     * @param query SQL query to execute
     * @param params query parameters
     * @return either (1) the row count for SQL Data Manipulation Language (DML) statements
     *         or (2) 0 for SQL statements that return nothing
     */
    int executeUpdate(String query, Object... params);

    /**
     * Executes the SQL query, which must be an SQL Data Manipulation Language (DML) statement,
     * such as <code>INSERT</code>, <code>UPDATE</code> or <code>DELETE</code>;
     * or an SQL statement that returns nothing, such as a DDL statement.
     *
     * @param query SQL query to execute
     * @param params collection of query parameters
     * @return either (1) the row count for SQL Data Manipulation Language (DML) statements
     *         or (2) 0 for SQL statements that return nothing
     */
    int executeUpdate(String query, Collection<Object> params);
}
